const mockYelpData = [
  {
    businesses: [
      {
        id: 'fake-restaurant',
        name: 'API Activation Required',
        image_url: 'https://via.placeholder.com/140',
        is_closed: false,
        url: 'https://167.71.51.18:3000/',
        review_count: 0,
        categories: [
          {
            alias: 'restaurants',
            title: 'Restaurants',
          },
        ],
        rating: 0,
        coordinates: {
          latitude: null,
          longitude: null,
        },
        transactions: [],
        price: '',
        location: {
          address1: '',
          address2: '',
          address3: '',
          city: '',
          zip_code: '',
          country: '',
          state: '',
          display_address: [],
        },
        phone: '',
        display_phone: '',
        distance: null,
        website: 'https://167.71.51.18:3000/',
        description:
          'To enable the live Yelp data, please visit the provided website link. Once you have done so, refresh the page to see updated restaurant listings.',
      },
      {
        id: 'c1ZcPZ7zAq_9uWICSFvdSQ',
        alias: 'the-chilis-espoo',
        name: "The Chili's",
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/GevRXmqQyGF5XdHn0Z1Nug/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/the-chilis-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 4,
        categories: [
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'tex-mex',
            title: 'Tex-Mex',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.195583879752,
          longitude: 24.765694047397,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Mankkaantie 6',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02180',
          country: 'FI',
          state: '18',
          display_address: ['Mankkaantie 6', '02180 Espoo', 'Finland'],
        },
        phone: '+35895021966',
        display_phone: '+358 9 5021966',
        distance: 3187.90054048448,
      },
      {
        id: '1iAN1JfMzF6pXlJFLe-bew',
        alias: 'la-cantine-helsinki',
        name: 'La Cantine',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/6Zna7VNorPnH5U0NlFf9ag/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/la-cantine-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 6,
        categories: [
          {
            alias: 'bistros',
            title: 'Bistros',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1994452,
          longitude: 24.8774014,
        },
        transactions: [],
        location: {
          address1: 'Laajalahdentie 17',
          address2: 'Bredviksvägen 17',
          address3: '',
          city: 'Helsinki',
          zip_code: '00330',
          country: 'FI',
          state: '18',
          display_address: [
            'Laajalahdentie 17',
            'Bredviksvägen 17',
            '00330 Helsinki',
            'Finland',
          ],
        },
        phone: '+3589499901',
        display_phone: '+358 9 499901',
        distance: 7115.158525707904,
      },
      {
        id: 'GCLHVJgzZ8g8tghbmvam7Q',
        alias: 'laguna-espoo-2',
        name: 'Laguna',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/cTPzhfhKm_Sxn1dNEfsb4w/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/laguna-espoo-2?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 2,
        categories: [
          {
            alias: 'venues',
            title: 'Venues & Event Spaces',
          },
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
          {
            alias: 'divebars',
            title: 'Dive Bars',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.2256813,
          longitude: 24.7279205,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Kuusiniemi 7',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02710',
          country: 'FI',
          state: '18',
          display_address: ['Kuusiniemi 7', '02710 Espoo', 'Finland'],
        },
        phone: '+358105488170',
        display_phone: '+358 10 5488170',
        distance: 1686.7415148619812,
      },
      {
        id: 'Vpq-1ExC2ev_udHFTnkfgA',
        alias: 'löyly-helsinki',
        name: 'Löyly',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/uFCifI0XO6r9dn_LTwfAag/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/l%C3%B6yly-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 45,
        categories: [
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
          {
            alias: 'localflavor',
            title: 'Local Flavor',
          },
          {
            alias: 'saunas',
            title: 'Saunas',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1518407742113,
          longitude: 24.9304517713644,
        },
        transactions: [],
        price: '€€€',
        location: {
          address1: 'Hernesaarenranta 4',
          address2: 'Ärtholmsstranden 4',
          address3: '',
          city: 'Helsinki',
          zip_code: '00150',
          country: 'FI',
          state: '18',
          display_address: [
            'Hernesaarenranta 4',
            'Ärtholmsstranden 4',
            '00150 Helsinki',
            'Finland',
          ],
        },
        phone: '+358961286550',
        display_phone: '+358 9 61286550',
        distance: 12442.110542721159,
      },
      {
        id: 'XRXCUKm_bxtXn5hzHxnqNQ',
        alias: 'pizza-makers-espoo',
        name: 'Pizza Makers',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/X2dY_E43_Nluk_iMnX8vbA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/pizza-makers-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 3,
        categories: [
          {
            alias: 'kebab',
            title: 'Kebab',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.2120399,
          longitude: 24.7697468,
        },
        transactions: [],
        location: {
          address1: 'Lansantie 23',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02630',
          country: 'FI',
          state: '18',
          display_address: ['Lansantie 23', '02630 Espoo', 'Finland'],
        },
        phone: '+3589522022',
        display_phone: '+358 9 522022',
        distance: 1448.3232829007284,
      },
      {
        id: 'D3EAsngYvnxesUw1ZlWRmA',
        alias: 'x-burger-espoo',
        name: 'X-Burger',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/3_kbOMZEuQEHXzCEI41VjA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/x-burger-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 4,
        categories: [
          {
            alias: 'burgers',
            title: 'Burgers',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1836205,
          longitude: 24.8313007,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Alvarinaukio 1',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02150',
          country: 'FI',
          state: '18',
          display_address: ['Alvarinaukio 1', '02150 Espoo', 'Finland'],
        },
        phone: '+358407368878',
        display_phone: '+358 40 7368878',
        distance: 6035.888805294978,
      },
      {
        id: 'LE02PQpjIRXMGGIn34CmCg',
        alias: 'pizzeria-shine-espoo-espoo',
        name: 'Pizzeria Shine Espoo',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/lKSujGFINqzy7zHANbr-sg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/pizzeria-shine-espoo-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 1,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 5.0,
        coordinates: {
          latitude: 60.2005806,
          longitude: 24.6700802,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Sokinsuontie 4',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02760',
          country: 'FI',
          state: '18',
          display_address: ['Sokinsuontie 4', '02760 Espoo', 'Finland'],
        },
        phone: '+35898632170',
        display_phone: '+358 9 8632170',
        distance: 5564.040106625503,
      },
      {
        id: 'PrnMEFF0Vjda7LeCPcJsZg',
        alias: 'ravintola-keilalahden-ranta-espoo',
        name: 'Ravintola Keilalahden Ranta',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/SXtYvP6QBSZM-3dD0HTF2A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ravintola-keilalahden-ranta-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 1,
        categories: [
          {
            alias: 'buffets',
            title: 'Buffets',
          },
        ],
        rating: 5.0,
        coordinates: {
          latitude: 60.1768472,
          longitude: 24.8327116,
        },
        transactions: [],
        location: {
          address1: 'Keilaranta 5',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02150',
          country: 'FI',
          state: '18',
          display_address: ['Keilaranta 5', '02150 Espoo', 'Finland'],
        },
        phone: '+358503452054',
        display_phone: '+358 50 3452054',
        distance: 6659.495537447924,
      },
      {
        id: 'S1Sg1Qscjf7iSgSoRHji2A',
        alias: 'carte-espoo',
        name: 'Carte',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/ZIVsN0RHFAocdd5YYGCuLQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/carte-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 1,
        categories: [
          {
            alias: 'eventservices',
            title: 'Event Planning & Services',
          },
          {
            alias: 'buffets',
            title: 'Buffets',
          },
        ],
        rating: 5.0,
        coordinates: {
          latitude: 60.2082214,
          longitude: 24.7661591,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Vitikka 2',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02630',
          country: 'FI',
          state: '18',
          display_address: ['Vitikka 2', '02630 Espoo', 'Finland'],
        },
        phone: '+3589466211',
        display_phone: '+358 9 466211',
        distance: 1800.9850236983368,
      },
      {
        id: 'qYJQFN_7zstfAjurKXX2Lw',
        alias: 'ravintola-haltia-espoo',
        name: 'Ravintola Haltia',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/uWnBD7lWYOwc3tw7-_fESQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ravintola-haltia-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 2,
        categories: [
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.2941083319244,
          longitude: 24.5566045492887,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Nuuksiontie 84',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02820',
          country: 'FI',
          state: '18',
          display_address: ['Nuuksiontie 84', '02820 Espoo', 'Finland'],
        },
        phone: '+358205644633',
        display_phone: '+358 20 5644633',
        distance: 13591.643061529327,
      },
      {
        id: 'sDyDDSdUTtWuVB04clG61A',
        alias: 'täffä-espoo-2',
        name: 'Täffä',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/opT7T3rokfKld-aUsCHI-A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/t%C3%A4ff%C3%A4-espoo-2?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 2,
        categories: [
          {
            alias: 'restaurants',
            title: 'Restaurants',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1861,
          longitude: 24.8330708,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Otakaari 22',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02150',
          country: 'FI',
          state: '18',
          display_address: ['Otakaari 22', '02150 Espoo', 'Finland'],
        },
        phone: '',
        display_phone: '',
        distance: 5896.441439585676,
      },
      {
        id: '7PIZbgjKDJbqGgVQJDhczA',
        alias: 'kathmandu-palace-espoo',
        name: 'Kathmandu Palace',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/P-Z30EN0CyJz-HXPjpCh4w/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/kathmandu-palace-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 4,
        categories: [
          {
            alias: 'himalayan',
            title: 'Himalayan/Nepalese',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.2222727491811,
          longitude: 24.8135110999135,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Timpurinkuja 2',
          address2: 'Timmermansgränden 2',
          address3: '',
          city: 'Espoo',
          zip_code: '02650',
          country: 'FI',
          state: '18',
          display_address: [
            'Timpurinkuja 2',
            'Timmermansgränden 2',
            '02650 Espoo',
            'Finland',
          ],
        },
        phone: '+358947892533',
        display_phone: '+358 9 47892533',
        distance: 3044.939122655542,
      },
      {
        id: 'B4_47hljsX5Oa62R37Q8cA',
        alias: 'maukas-espoo',
        name: 'MAUKAS',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/84VNA3cBW9oOiYyB-BlGrA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/maukas-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 4,
        categories: [
          {
            alias: 'breakfast_brunch',
            title: 'Breakfast & Brunch',
          },
          {
            alias: 'modern_european',
            title: 'Modern European',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1828465,
          longitude: 24.8280796,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Vuorimiehentie 5',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02150',
          country: 'FI',
          state: '18',
          display_address: ['Vuorimiehentie 5', '02150 Espoo', 'Finland'],
        },
        phone: '+358407050157',
        display_phone: '+358 40 7050157',
        distance: 5979.740391442703,
      },
      {
        id: 'V7x6I5wBmbQ7xCwBPC1o9A',
        alias: 'grilli-ribis-espoo',
        name: 'Grilli Ribis',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/b3UNhdzmrO3k50lCAODT2w/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/grilli-ribis-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 1,
        categories: [
          {
            alias: 'bbq',
            title: 'Barbeque',
          },
        ],
        rating: 5.0,
        coordinates: {
          latitude: 60.17659,
          longitude: 24.8017693,
        },
        transactions: [],
        location: {
          address1: 'Kauppamiehentie 1',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02100',
          country: 'FI',
          state: '18',
          display_address: ['Kauppamiehentie 1', '02100 Espoo', 'Finland'],
        },
        phone: '+35894551780',
        display_phone: '+358 9 4551780',
        distance: 5758.004451470778,
      },
      {
        id: 'mFElUbRiZIfwpEkWJyXbVw',
        alias: 'fisken-på-disken-helsinki',
        name: 'Fisken på Disken',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/2ICkdoNU1fVdEuFr0mxOXw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/fisken-p%C3%A5-disken-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 12,
        categories: [
          {
            alias: 'seafood',
            title: 'Seafood',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1693314661659,
          longitude: 24.9338641883605,
        },
        transactions: [],
        location: {
          address1: 'Urho Kekkosen katu 1',
          address2: 'Urho Kekkonens gata 1',
          address3: '',
          city: 'Helsinki',
          zip_code: '00100',
          country: 'FI',
          state: '18',
          display_address: [
            'Urho Kekkosen katu 1',
            'Urho Kekkonens gata 1',
            '00100 Helsinki',
            'Finland',
          ],
        },
        phone: '+358401971157',
        display_phone: '+358 40 1971157',
        distance: 11442.821385778767,
      },
      {
        id: '7NaZX8TNgYg5kjpye7Fz9Q',
        alias: 'bembölen-kahvitupa-espoo',
        name: 'Bembölen Kahvitupa',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/8af6lz_3s1G9f-mr10XvnQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bemb%C3%B6len-kahvitupa-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 14,
        categories: [
          {
            alias: 'comfortfood',
            title: 'Comfort Food',
          },
          {
            alias: 'coffee',
            title: 'Coffee & Tea',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.222816553072,
          longitude: 24.6739110313885,
        },
        transactions: [],
        price: '€',
        location: {
          address1: 'Bellinmäki 1',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02740',
          country: 'FI',
          state: '18',
          display_address: ['Bellinmäki 1', '02740 Espoo', 'Finland'],
        },
        phone: '+35898632917',
        display_phone: '+358 9 8632917',
        distance: 4672.21861302842,
      },
      {
        id: 'Fv970NsjEZqzYcCZUFxM-A',
        alias: 'meritorppa-helsinki-2',
        name: 'Meritorppa',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/aZOorunUsV4S0YaGWKD9mg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/meritorppa-helsinki-2?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 11,
        categories: [
          {
            alias: 'seafood',
            title: 'Seafood',
          },
          {
            alias: 'lounges',
            title: 'Lounges',
          },
          {
            alias: 'tradamerican',
            title: 'American (Traditional)',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1922493,
          longitude: 24.8735199,
        },
        transactions: [],
        price: '€€€€',
        location: {
          address1: 'Kalastajatorpantie 1',
          address2: null,
          address3: null,
          city: 'Helsinki',
          zip_code: '00330',
          country: 'FI',
          state: '18',
          display_address: [
            'Kalastajatorpantie 1',
            '00330 Helsinki',
            'Finland',
          ],
        },
        phone: '+358945811',
        display_phone: '+358 9 45811',
        distance: 7242.771428691766,
      },
      {
        id: 'vpGleEHwCj47WpYCytXnwg',
        alias: 'kylä-espoo',
        name: 'Kylä',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/HWEu77aNX60GlD92I-t4hw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/kyl%C3%A4-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 1,
        categories: [
          {
            alias: 'modern_european',
            title: 'Modern European',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1766391712164,
          longitude: 24.8047194747004,
        },
        transactions: [],
        location: {
          address1: 'Tapiontori 3',
          address2: '',
          address3: '',
          city: 'Espoo',
          zip_code: '02100',
          country: 'FI',
          state: '18',
          display_address: ['Tapiontori 3', '02100 Espoo', 'Finland'],
        },
        phone: '+358102310430',
        display_phone: '+358 10 2310430',
        distance: 5856.20897827722,
      },
      {
        id: 'igAGZDc4Y5gTF-rKzkAvdA',
        alias: 'haukilahden-paviljonki-espoo',
        name: 'Haukilahden Paviljonki',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/oMHGHFpdVMj0BtVVIx8H1A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/haukilahden-paviljonki-espoo?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 8,
        categories: [
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1551119450184,
          longitude: 24.7733545303345,
        },
        transactions: [],
        price: '€€€',
        location: {
          address1: 'Mellstenintie 12',
          address2: null,
          address3: null,
          city: 'Espoo',
          zip_code: '02170',
          country: 'FI',
          state: '18',
          display_address: ['Mellstenintie 12', '02170 Espoo', 'Finland'],
        },
        phone: '+358108419190',
        display_phone: '+358 10 8419190',
        distance: 7707.150552071061,
      },
      {
        id: 'aUUT4i8bzSLj_aOYMYrb2Q',
        alias: 'passio-keittiö-ja-baari-helsinki-3',
        name: 'PASSIO Keittiö ja Baari',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/99pABzg8Px2Xuhz5PROIPw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/passio-keitti%C3%B6-ja-baari-helsinki-3?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 33,
        categories: [
          {
            alias: 'modern_european',
            title: 'Modern European',
          },
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
        ],
        rating: 5.0,
        coordinates: {
          latitude: 60.1670838,
          longitude: 24.9369496,
        },
        transactions: [],
        price: '€€€€',
        location: {
          address1: 'Kalevankatu 13',
          address2: 'Kalevagatan 13',
          address3: '',
          city: 'Helsinki',
          zip_code: '00100',
          country: 'FI',
          state: '18',
          display_address: [
            'Kalevankatu 13',
            'Kalevagatan 13',
            '00100 Helsinki',
            'Finland',
          ],
        },
        phone: '+358207352040',
        display_phone: '+358 20 7352040',
        distance: 11721.010371909577,
      },
      {
        id: 'ydETYp71H1XilFUwpS3Cvw',
        alias: 'il-birrificio-helsinki',
        name: 'Il Birrificio',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/Zz3ak2j6Hcs0Xn1R7pdlAg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/il-birrificio-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 17,
        categories: [
          {
            alias: 'bistros',
            title: 'Bistros',
          },
          {
            alias: 'breweries',
            title: 'Breweries',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1631508,
          longitude: 24.9381199,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Fredrikinkatu 22',
          address2: '',
          address3: '',
          city: 'Helsinki',
          zip_code: '00120',
          country: 'FI',
          state: '18',
          display_address: ['Fredrikinkatu 22', '00120 Helsinki', 'Finland'],
        },
        phone: '+3589651939',
        display_phone: '+358 9 651939',
        distance: 12135.96406112101,
      },
      {
        id: 'wdceec2XGw4PYJ95C-emtQ',
        alias: 'bryggeri-helsinki',
        name: 'Bryggeri',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/JYlOk8ISNMc-M46vnEATlA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bryggeri-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 47,
        categories: [
          {
            alias: 'breweries',
            title: 'Breweries',
          },
          {
            alias: 'scandinavian',
            title: 'Scandinavian',
          },
          {
            alias: 'beerbar',
            title: 'Beer Bar',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1680503,
          longitude: 24.9519812,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Sofiankatu 2',
          address2: '',
          address3: '',
          city: 'Helsinki',
          zip_code: '00170',
          country: 'FI',
          state: '18',
          display_address: ['Sofiankatu 2', '00170 Helsinki', 'Finland'],
        },
        phone: '+358102352500',
        display_phone: '+358 10 2352500',
        distance: 12373.683220972809,
      },
      {
        id: 'dV9vHFho323hBatMUk5bKQ',
        alias: 'korean-kitchen-espoo-2',
        name: 'Korean Kitchen',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/yrkQD3-WWkw73wvu4wBhQw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/korean-kitchen-espoo-2?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 4,
        categories: [
          {
            alias: 'korean',
            title: 'Korean',
          },
        ],
        rating: 4.0,
        coordinates: {
          latitude: 60.1627951123895,
          longitude: 24.7379892072772,
        },
        transactions: [],
        location: {
          address1: 'Piispansilta 9',
          address2: 'Biskopsbron 9',
          address3: '',
          city: 'Espoo',
          zip_code: '02230',
          country: 'FI',
          state: '18',
          display_address: [
            'Piispansilta 9',
            'Biskopsbron 9',
            '02230 Espoo',
            'Finland',
          ],
        },
        phone: '+358400969667',
        display_phone: '+358 40 0969667',
        distance: 6902.4557253981775,
      },
      {
        id: 'pHovMXxRaQ_qmiuHDgwbgg',
        alias: 'flying-dutch-helsinki',
        name: 'Flying Dutch',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/FjUVvsbgONyB2tj6fWzUQQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/flying-dutch-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 15,
        categories: [
          {
            alias: 'musicvenues',
            title: 'Music Venues',
          },
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'burgers',
            title: 'Burgers',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1768941813989,
          longitude: 24.9490928649902,
        },
        transactions: [],
        price: '€€',
        location: {
          address1: 'Pitkänsillanranta 2',
          address2: 'Långbrokajen 2',
          address3: '',
          city: 'Helsinki',
          zip_code: '00530',
          country: 'FI',
          state: '18',
          display_address: [
            'Pitkänsillanranta 2',
            'Långbrokajen 2',
            '00530 Helsinki',
            'Finland',
          ],
        },
        phone: '+358400974345',
        display_phone: '+358 40 0974345',
        distance: 11764.956127323108,
      },
      {
        id: '77VEtM2xAYTkAdR7bYvZnQ',
        alias: 'kitzens-helsinki',
        name: 'Kitzens',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/ZvzKSydwuZDQQGF-har_Ng/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/kitzens-helsinki?adjust_creative=-IWsB9J0xMTcH9GoRR03tQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-IWsB9J0xMTcH9GoRR03tQ',
        review_count: 3,
        categories: [
          {
            alias: 'modern_european',
            title: 'Modern European',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 60.1724091,
          longitude: 24.9457607,
        },
        transactions: [],
        price: '€€€',
        location: {
          address1: 'Mikonkatu 23',
          address2: '',
          address3: '',
          city: 'Helsinki',
          zip_code: '00100',
          country: 'FI',
          state: '18',
          display_address: ['Mikonkatu 23', '00100 Helsinki', 'Finland'],
        },
        phone: '+358201234800',
        display_phone: '+358 20 1234800',
        distance: 11802.740913980044,
      },
    ],
    total: 1200,
    region: {
      center: {
        longitude: 24.75848455114475,
        latitude: 60.22402875776225,
      },
    },
  },
];
export default mockYelpData;
